booking/booking/Controllers/ClassicsController.cs
using Microsoft.AspNetCore.Mvc;
using booking.Models;
using booking.Service.Interface;
using Microsoft.AspNetCore.Authorization;

namespace booking.Controllers
{
    public class ClassicsController : GenericController<Classic>
    {
        public ClassicsController(IGenericService<Classic> genericService) : base(genericService)
        {
            
        }
        
        
    }
}

booking/booking/Controllers/OpenAirsController.cs
using booking.Models;
using booking.Service.Interface;

namespace booking.Controllers
{
    public class OpenAirsController : GenericController<OpenAir>
    {

        public OpenAirsController(IGenericService<OpenAir> genericService) : base(genericService)
        {
  
        }
        
    }
}

booking/booking/Controllers/PartiesController.cs
using booking.Models;
using booking.Service.Interface;

namespace booking.Controllers
{
    public class PartiesController : GenericController<Party>
    {
        public PartiesController(IGenericService<Party> genericService) : base(genericService)
        {
            
        }       

    }
}

booking/booking/Controllers/TicketsController.cs
using System;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using booking.Models;
using booking.Service.Interface;
using booking.Service;
using booking.ViewModel;

namespace booking.Controllers
{
    public class TicketsController : Controller
    {
        private readonly ITicketService _ticketService;
        private readonly IEmailService _emailService;

        public TicketsController(ITicketService ticketService, IEmailService emailService)
        {
            _ticketService = ticketService;
            _emailService = emailService;
        }

        //// GET: Tickets
        [HttpGet]
        public IActionResult Index()
        {
            return View(_ticketService.GetAllTickets());
        }

        public IActionResult GetAllTicketByEmail(string userName)
        {
            TicketViewModel tViewModel = new TicketViewModel();
            tViewModel.listTickets = _ticketService.GetListTicketsByEmail(userName);

            return View(tViewModel.listTickets);
        }

        // GET: Tickets/Details/5
        [HttpGet]
        public IActionResult Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var ticket =  _ticketService.GetTicketById(id);

            if (ticket == null)
            {
                return NotFound();
            }

            return View(ticket);
        }

        [HttpGet]
        public IActionResult BookTicket(int? idConcert, string Email, string performer)
        {
            if (idConcert == null)
            {
                return NotFound();
            }
            if(String.IsNullOrEmpty(Email))
            {
                return Redirect("~/Identity/Account/Login");
            }

            TicketViewModel ticketVM = new TicketViewModel(); 
            ticketVM.ticket = _ticketService.BookTicket(idConcert, Email, performer);

            return View(ticketVM);
        }        

        [HttpPost]
        public async Task<IActionResult> BookTicketAsync(TicketViewModel ticketVm)
        {
            if (ModelState.IsValid)
            {
                if (await _ticketService.AddBookingTicket(ticketVm))
                {
                    if (_ticketService.CheckAvailableTicketsByConcertId(ticketVm.ticket.ConcertId, ticketVm.ticket.AmountPlaces))
                    {
                        _ticketService.changeAmountTicketsForSelectConcert(ticketVm.ticket.ConcertId, ticketVm.ticket.AmountPlaces, false);

                        await _emailService.SendEmailAsync(ticketVm.ticket.UserName,
                                                            "Подтверждение бронирования билета(ов) для " + ticketVm.ticket.UserName,
                                                            "Вы оформили бронь на концерт исполнителя - " + ticketVm.ticket.performer + ", количество бронируемых мест - " + ticketVm.ticket.AmountPlaces);

                    }
                }
                return RedirectToAction("GetAllTicketByEmail", new { userName = ticketVm.ticket.UserName }); 
            }
            else 
            {
                return View(ticketVm);                
            }            
        }

        [HttpGet]
        public IActionResult CancelBooking(int idTicket)
        {
            if (idTicket == 0)
            {
                return NotFound();
            }
            var userName = _ticketService.GetUserNameByTicketId(idTicket);
            _ticketService.CancelBooking(idTicket);

            return RedirectToAction("GetAllTicketByEmail", new { userName = userName });
        }
    }
}

booking/booking/Views/Shared/_ConcertPartialView.cshtml
@model booking.Models.Concert

<div class="form-group">
    <label asp-for="Performer" class="control-label"></label>
    <input asp-for="Performer" class="form-control" />
    <span asp-validation-for="Performer" class="text-danger"></span>
</div>
<div class="form-group">
    <label asp-for="AmounTickets" class="control-label"></label>
    <input asp-for="AmounTickets" class="form-control" />
    <span asp-validation-for="AmounTickets" class="text-danger"></span>
</div>
<div class="form-group">
    <label asp-for="Date" class="control-label"></label>
    <input asp-for="Date" class="form-control" />
    <span asp-validation-for="Date" class="text-danger"></span>
</div>
<div class="form-group">
    <label asp-for="Geo_lat" class="control-label"></label>
    <input asp-for="Geo_lat" class="form-control" />
    <span asp-validation-for="Geo_lat" class="text-danger"></span>
</div>
<div class="form-group">
    <label asp-for="Geo_lng" class="control-label"></label>
    <input asp-for="Geo_lng" class="form-control" />
    <span asp-validation-for="Geo_lng" class="text-danger"></span>
</div>

booking/booking/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">

@using Microsoft.AspNetCore.Identity
 
@inject SignInManager<IdentityUser> SignInManager
@inject UserManager<IdentityUser> UserManager
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - booking</title>
    <link rel="stylesheet" href="~/dist/bundle.css" asp-append-version="true" /> 
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="HomePage">booking</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        @if (SignInManager.IsSignedIn(User))
                        {
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-controller="Tickets" asp-route-username="@User.Identity.Name" asp-action="GetAllTicketByEmail">My tickets</a>
                            </li>
                        }

                        @if (SignInManager.IsSignedIn(User) && User.IsInRole("Admin"))
                        {
                            <li>
                                <div class="dropdown">
                                    <button class="btn dropdown-toggle  text-dark" type="button" id="dropdownMenuButton" data-bs-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                                        Add concert
                                    </button>
                                    <div class="dropdown-menu bg-light" aria-labelledby="dropdownMenuButton">
                                        <a class="dropdown-item text-dark bg-light" asp-controller="Parties" asp-action="Create">Add Party</a>
                                        <a class="dropdown-item text-dark bg-light" asp-controller="Classics" asp-action="Create">Add Classic</a>
                                        <a class="dropdown-item text-dark bg-light" asp-controller="OpenAirs" asp-action="Create">Add OpenAir</a>

                                    </div>
                                </div>
                            </li>

                            <li>
                                <div class="dropdown">
                                    <button class="btn dropdown-toggle  text-dark" type="button" id="dropdownMenuButton" data-bs-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                                        Edit concert
                                    </button>
                                    <div class="dropdown-menu bg-light" aria-labelledby="dropdownMenuButton">
                                        <a class="dropdown-item text-dark bg-light" asp-controller="Parties" asp-action="Index">Edit Parties</a>
                                        <a class="dropdown-item text-dark bg-light" asp-controller="Classics" asp-action="Index">Edit Classics</a>
                                        <a class="dropdown-item text-dark bg-light" asp-controller="OpenAirs" asp-action="Index">Edit OpenAirs</a>

                                    </div>
                                </div>
                            </li>
                        }

                    </ul>
                    <partial name="_LoginPartial" />
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>
    <script src="~/dist/bundle.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>