booking/booking/Controllers/AdminAccountController.cs
using booking.Service;
using booking.ViewModel;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using System;

namespace booking.Controllers
{
    [Authorize]
    public class AdminAccountController : Controller
    {
        private readonly IAdminService _adminService;
        private readonly IServiceProvider _serviceProvider;

        public AdminAccountController( IAdminService adminService, IServiceProvider serviceProvider)
        {            
            _adminService = adminService;
            _serviceProvider = serviceProvider;
        }

        public IActionResult Index()
        { 
            UserViewModel userViewModel = new UserViewModel();
            userViewModel.userModels = _adminService.GetListUserWithRoles();
            userViewModel.identityUsers = _adminService.GetUsers();
            userViewModel.userNameIsAdmin = User.IsInRole("");
            

            return View(userViewModel);
        }

        [Authorize(Roles = "Admin")]
        public ActionResult DeleteUserRole(string id, string role)
        {
            _adminService.DeleteUserRole(id, role);
            return RedirectToAction(nameof(Index));
        }
       
        [Authorize(Roles = "Admin")]
        public ActionResult EditUser(string id)
        {
            if (string.IsNullOrEmpty(id))
            {
                return NotFound();
            }

            var userModel = _adminService.GetUserModel(id);
            if (userModel == null)
            {
                return NotFound();
            }
            return View(userModel);
        }
        [Authorize(Roles = "Admin")]
        [HttpPost]
        public ActionResult EditUser(UserModel userModel)
        {
            _adminService.EditUser(userModel, _serviceProvider);

            return RedirectToAction(nameof(Index));
        }
    }
}

booking/booking/Controllers/RolesController.cs
using booking.Service;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using System.Threading.Tasks;

namespace booking.Controllers
{
    [Authorize]
    public class RolesController : Controller
    {       

        private readonly IRoleService _roleService;

        public RolesController(IRoleService roleService)
        {
            _roleService = roleService;
            
        }

        [Authorize(Roles = "User")]
        private async Task GiveAdminRoles(string name)
        {
            await _roleService.GetAdminRole(name);                       
        }
        
        private async Task GiveUserRoles(string name)
        {
            await _roleService.GetUserRole(name);
        }

        [Authorize(Roles = "User")]
        public async Task<ActionResult> giveAdminRole(string id)
        {
            await GiveAdminRoles(id);

            return Redirect("~/AdminAccount/Index");
        }

        public async Task<ActionResult> giveUserRole(string id)
        {
            await GiveUserRoles(id);

            return Redirect("~/AdminAccount/Index");
        }
    }
}

booking/booking/Views/AdminAccount/EditUser.cshtml
@model booking.ViewModel.UserModel

@{
    ViewData["Title"] = "EditUser";
}

<h1>EditUser</h1>

<h4>UserModel</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="EditUser">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <input type="hidden" asp-for="Id" />
            <div hidden class="form-group">
                <label asp-for="Role" class="control-label"></label>
                <input asp-for="Role" class="form-control" />
                <span asp-validation-for="Role" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Email" class="control-label"></label>
                <input asp-for="Email" class="form-control" />
                <span asp-validation-for="Email" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Save" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

booking/booking/Views/AdminAccount/Index.cshtml
@model booking.ViewModel.UserViewModel

@{
    ViewData["Title"] = "Index";
}

<ul class="nav nav-tabs" id="myTab" role="tablist">
    <li class="nav-item" role="presentation">
        <a class="nav-link active" id="user-tab" data-bs-toggle="tab" href="#user" role="tab" aria-controls="user" aria-selected="true">User</a>
    </li>
    <li class="nav-item" role="presentation">
        <a class="nav-link" id="role-tab" data-bs-toggle="tab" href="#role" role="tab" aria-controls="role" aria-selected="false">Role</a>
    </li>
    <li class="nav-item" role="presentation">
        <a class="nav-link" id="edit-tab" data-bs-toggle="tab" href="#edit" role="tab" aria-controls="edit" aria-selected="false">Edit</a>
    </li>
</ul>
<div class="tab-content" id="myTabContent">
    <div class="tab-pane fade show active" id="user" role="tabpanel" aria-labelledby="user-tab">
        <table class="table">
            <thead>
                <tr>
                    <th>
                        <div>№</div>
                    </th>

                    <th>
                        <div>Email</div>
                    </th>

                    <th></th>
                </tr>
            </thead>
            <tbody>
                @{ int i = 0;}
                @foreach (var item in Model.identityUsers)
                {
                    <tr>
                        <td>
                            @{
                                i++;
                            }<div>@i</div>
                        </td>

                        <td>
                            @Html.DisplayFor(modelItem => item.Email)
                        </td>

                        <td>
                            <a asp-controller="Roles" asp-action="giveAdminRole" asp-route-id=@item.Id class="btn btn-outline-secondary">
                                <span title="Дать роль админа" class="fas fa-unlock"></span>
                            </a>
                            <a asp-controller="Roles" asp-action="giveUserRole" asp-route-id=@item.Id class="btn btn-outline-secondary">
                                <span title="Дать роль юзера" class="fas fa-user"></span>
                            </a>
                        </td>
                    </tr>
                }
            </tbody>
        </table>

    </div>
    <div class="tab-pane fade" id="role" role="tabpanel" aria-labelledby="role-tab">
        <table class="table">
            <thead>
                <tr>
                    <th>
                        <div>№</div>
                    </th>

                    <th>
                        <div>Email</div>
                    </th>

                    <th>
                        <div>Role</div>
                    </th>

                    <th></th>
                </tr>
            </thead>
            <tbody>
                @{ int j = 0;}
                @foreach (var item in Model.userModels)
                {
                    <tr>
                        <td>
                            @{
                                j++;
                            }<div>@j</div>
                        </td>

                        <td>
                            @Html.DisplayFor(modelItem => item.Email)
                        </td>

                        <td>
                            @Html.DisplayFor(modelItem => item.Role)
                        </td>

                        <td>
                            <a asp-controller="AdminAccount" asp-action="DeleteUserRole" asp-route-id=@item.Id asp-route-role="@item.Role" class="btn btn-outline-secondary">
                                <span title="Удалить роль пользователя" class="fas fa-trash"></span>
                            </a>
                        </td>
                    </tr>
                }
            </tbody>
        </table>

    </div>
    <div class="tab-pane fade" id="edit" role="tabpanel" aria-labelledby="edit-tab">
        <table class="table">
            <thead>
                <tr>
                    <th>
                        <div>№</div>
                    </th>

                    <th>
                        <div>Email</div>
                    </th>

                    <th>
                        <div>Role</div>
                    </th>

                    <th></th>
                </tr>
            </thead>
            <tbody>
                @{ int k = 0;}
                @foreach (var item in Model.userModels)
                {
                    <tr>
                        <td>
                            @{
                                k++;
                            }<div>@k</div>
                        </td>

                        <td>
                            @Html.DisplayFor(modelItem => item.Email)
                        </td>

                        <td>
                            <a asp-controller="AdminAccount" asp-action="EditUser" asp-route-id=@item.Id class="btn btn-outline-secondary">
                                <span title="Редактировать юзера" class="fas fa-pencil-alt"></span>
                            </a>
                        </td>
                    </tr>
                }
            </tbody>
        </table>

    </div>
</div>